################
### MONITORS ###
################

monitor=,preferred,auto,1

###################
### ENVIRONMENT ###
###################

env = XCURSOR_SIZE,24

#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = dunst
#exec-once = hyprpaper

###################
### INPUT ###
###################

input {
    kb_layout = us

    follow_mouse = 1

    touchpad {
        natural_scroll = false
    }

    sensitivity = 0
}

###################
### GENERAL ###
###################

general {
    gaps_in = 5
    gaps_out = 10

    border_size = 2

    layout = dwindle
}

###################
### DECORATION ###
###################

decoration {
    rounding = 8
}

###################
### ANIMATIONS ###
###################

animations {
    enabled = true
}

###################
### KEYBINDINGS ###
###################

$mainMod = SUPER

bind = $mainMod, Return, exec, kitty
bind = $mainMod, D, exec, wofi --show drun
bind = $mainMod, Q, killactive
bind = $mainMod SHIFT, E, exit

bind = $mainMod, F, fullscreen

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4

###################
### MOUSE ###
###################

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
