###################
### ENVIRONMENT ###
###################

env = XCURSOR_SIZE,24
env = XMODIFIERS,@im=fcitx
env = GTK_IM_MODULE,fcitx
env = QT_IM_MODULE,fcitx
env = SDL_IM_MODULE,fcitx
env = INPUT_METHOD,fcitx
env = GLFW_IM_MODULE,fcitx

#################
### INPUT ###
#################

input {
    kb_layout = us

    follow_mouse = 1

    touchpad {
        natural_scroll = false
    }

    sensitivity = 0
}
